"""
重建所有书签：清库 → 重新入高质量网站，中文描述，分类整理
工具类重点：在线转换、免费邮箱、虚拟电话、VPN等
"""
import mysql.connector
import re

DB = {'host': 'localhost', 'user': 'root', 'password': '123456', 'database': 'pj1', 'charset': 'utf8mb4'}

# ======================== 所有网站数据（中文描述，精概） ========================

SITES = {
    'work': [
        ('GitHub', 'https://github.com', '全球最大代码托管与协作平台', '🐙'),
        ('GitLab', 'https://gitlab.com', '完整 DevOps 生命周期管理', '🦊'),
        ('Gitee', 'https://gitee.com', '中国代码托管与开源社区', '🇨🇳'),
        ('Stack Overflow', 'https://stackoverflow.com', '程序员技术问答社区', '❓'),
        ('VS Code', 'https://vscode.dev', '微软在线代码编辑器', '💻'),
        ('CodePen', 'https://codepen.io', '前端代码在线编辑与展示', '✏️'),
        ('CodeSandbox', 'https://codesandbox.io', '云端 Web 开发沙盒环境', '📦'),
        ('Replit', 'https://replit.com', '在线编程协作环境', '🔄'),
        ('Jira', 'https://www.atlassian.com/software/jira', '敏捷项目管理与缺陷跟踪', '📋'),
        ('Trello', 'https://trello.com', '看板式轻量项目管理工具', '📌'),
        ('Asana', 'https://asana.com', '团队任务协调与项目规划', '✅'),
        ('Monday.com', 'https://monday.com', '可视化工作操作系统', '📊'),
        ('Linear', 'https://linear.app', '极简高效的项目追踪工具', '📐'),
        ('ClickUp', 'https://clickup.com', '一体化生产力与项目管理平台', '⚡'),
        ('Notion', 'https://www.notion.so', '全能笔记、知识库与协作空间', '📝'),
        ('Slack', 'https://slack.com', '团队即时通讯与频道协作', '💬'),
        ('Microsoft Teams', 'https://teams.microsoft.com', '微软视频会议与团队协作', '🪟'),
        ('Zoom', 'https://zoom.us', '跨平台高清视频会议', '📹'),
        ('Google Meet', 'https://meet.google.com', '谷歌视频会议服务', '📹'),
        ('Discord', 'https://discord.com', '游戏与社区语音文字聊天', '🎮'),
        ('Figma', 'https://www.figma.com', '云端协作 UI/UX 设计工具', '🎨'),
        ('Canva', 'https://www.canva.com', '在线简易平面设计与排版', '🎨'),
        ('Adobe Creative Cloud', 'https://www.adobe.com/creativecloud', '专业创意设计全套工具', '🖌️'),
        ('Dribbble', 'https://dribbble.com', '全球设计师作品展示社区', '🏀'),
        ('Behance', 'https://www.behance.net', 'Adobe 旗下创意作品集平台', '🖼️'),
        ('Miro', 'https://miro.com', '在线协作白板与思维导图', '🖊️'),
        ('Excalidraw', 'https://excalidraw.com', '手绘风格在线白板绘图', '✏️'),
        ('Airtable', 'https://airtable.com', '电子表格与数据库混合协作', '📊'),
        ('Google Workspace', 'https://workspace.google.com', '谷歌云端办公套件全家桶', '📧'),
        ('Microsoft 365', 'https://www.office.com', '微软 Office 云端办公套件', '📄'),
        ('Dropbox', 'https://www.dropbox.com', '跨平台云存储与文件同步', '📦'),
        ('Google Drive', 'https://drive.google.com', '谷歌免费云存储与协作', '💾'),
        ('OneDrive', 'https://onedrive.live.com', '微软个人与企业云存储', '☁️'),
        ('Box', 'https://www.box.com', '企业级安全云内容管理', '📁'),
        ('Zapier', 'https://zapier.com', '数千应用之间的自动化连接器', '⚡'),
        ('Make', 'https://www.make.com', '可视化工作流自动化编排', '🧩'),
        ('IFTTT', 'https://ifttt.com', '条件触发式应用联动自动化', '🔗'),
        ('Notion Calendar', 'https://calendar.notion.so', 'Notion 生态日程管理', '📅'),
        ('Calendly', 'https://calendly.com', '智能日程预约与时间管理', '📅'),
        ('Todoist', 'https://todoist.com', '跨平台极简待办事项管理', '✅'),
        ('Evernote', 'https://evernote.com', '老牌跨平台笔记与知识整理', '📓'),
        ('Obsidian', 'https://obsidian.md', '本地优先的双向链接笔记', '💎'),
        ('Grammarly', 'https://www.grammarly.com', 'AI 英语写作语法检查助手', '✍️'),
        ('DeepL', 'https://www.deepl.com', '高质量 AI 多语言翻译工具', '🌍'),
        ('Google Translate', 'https://translate.google.com', '谷歌免费多语种在线翻译', '🌍'),
        ('Stripe', 'https://stripe.com', '全球开发者友好支付网关', '💳'),
        ('PayPal', 'https://www.paypal.com', '全球通用在线支付平台', '💰'),
        ('Square', 'https://squareup.com', '中小商户支付与POS系统', '💳'),
        ('DocuSign', 'https://www.docusign.com', '全球领先电子签名服务', '✍️'),
        ('HelloSign', 'https://www.hellosign.com', 'Dropbox 旗下电子签约工具', '🖋️'),
    ],
    'study': [
        ('Coursera', 'https://www.coursera.org', '世界名校认证在线课程平台', '🎓'),
        ('edX', 'https://www.edx.org', '哈佛MIT发起的名校免费课程', '🏛️'),
        ('Udemy', 'https://www.udemy.com', '海量职业技能视频课程市场', '📚'),
        ('Khan Academy', 'https://www.khanacademy.org', '全年龄段免费教育公益平台', '🏫'),
        ('Udacity', 'https://www.udacity.com', '前沿技术纳米学位与实训', '🎯'),
        ('Codecademy', 'https://www.codecademy.com', '交互式在线编程入门学习', '💻'),
        ('freeCodeCamp', 'https://www.freecodecamp.org', '免费全栈编程学习与证书', '🆓'),
        ('LeetCode', 'https://leetcode.com', '程序员算法面试刷题必备', '🧩'),
        ('HackerRank', 'https://www.hackerrank.com', '编程挑战与企业技术面试', '🏆'),
        ('CodeWars', 'https://www.codewars.com', '游戏化编程道场实战训练', '⚔️'),
        ('Pluralsight', 'https://www.pluralsight.com', '企业级技术技能评估平台', '📖'),
        ('LinkedIn Learning', 'https://www.linkedin.com/learning', '职场技能视频课程订阅', '🎬'),
        ('Skillshare', 'https://www.skillshare.com', '创意技能与设计课程社区', '✨'),
        ('Duolingo', 'https://www.duolingo.com', '游戏化多语言免费学习应用', '🦉'),
        ('Memrise', 'https://www.memrise.com', '沉浸式多语言词汇记忆', '🌍'),
        ('Busuu', 'https://www.busuu.com', '社交化在线语言学习社区', '🗣️'),
        ('HelloTalk', 'https://www.hellotalk.com', '语言交换聊天交友学习', '💬'),
        ('Quizlet', 'https://quizlet.com', '闪卡式记忆与学习工具', '🃏'),
        ('Brilliant', 'https://brilliant.org', '互动式数学科学思维训练', '💡'),
        ('MIT OpenCourseWare', 'https://ocw.mit.edu', '麻省理工学院免费课件库', '🏛️'),
        ('Stanford Online', 'https://online.stanford.edu', '斯坦福大学在线教育平台', '🌲'),
        ('Harvard Online', 'https://online-learning.harvard.edu', '哈佛大学在线课程中心', '🎓'),
        ('W3Schools', 'https://www.w3schools.com', 'Web 前端技术入门教程网站', '🌐'),
        ('MDN Web Docs', 'https://developer.mozilla.org', 'Mozilla 官方 Web 标准文档', '📘'),
        ('GeeksforGeeks', 'https://www.geeksforgeeks.org', '印度计算机科学知识宝库', '💡'),
        ('TutorialsPoint', 'https://www.tutorialspoint.com', '多领域编程技术教程大全', '📗'),
        ('Dev.to', 'https://dev.to', '全球开发者写作与交流社区', '✍️'),
        ('Medium', 'https://medium.com', '全球深度长文阅读与写作', '📝'),
        ('ArXiv', 'https://arxiv.org', '康奈尔大学预印本学术论文', '📄'),
        ('Google Scholar', 'https://scholar.google.com', '谷歌学术文献搜索引擎', '📖'),
        ('ResearchGate', 'https://www.researchgate.net', '全球科研人员学术社交平台', '🔬'),
        ('Wikipedia', 'https://www.wikipedia.org', '自由开放的在线百科全书', '📖'),
        ('Britannica', 'https://www.britannica.com', '大英百科全书数字在线版', '🏛️'),
        ('百度百科', 'https://baike.baidu.com', '中文世界最大的百科全书', '📖'),
        ('知乎', 'https://www.zhihu.com', '中文高质量知识问答社区', '❔'),
        ('B站', 'https://www.bilibili.com', '弹幕视频与海量学习资源社区', '📺'),
        ('中国大学MOOC', 'https://www.icourse163.org', '中国高校精品在线课程平台', '🇨🇳'),
        ('学堂在线', 'https://www.xuetangx.com', '清华大学发起的在线课程平台', '🏫'),
        ('Wolfram Alpha', 'https://www.wolframalpha.com', '计算型知识搜索引擎', '🧮'),
        ('Desmos', 'https://www.desmos.com', '在线数学图形计算器', '📈'),
        ('GeoGebra', 'https://www.geogebra.org', '动态数学教学与绘图工具', '📐'),
        ('Goodreads', 'https://www.goodreads.com', '全球最大读书社区与书评', '📚'),
        ('Project Gutenberg', 'https://www.gutenberg.org', '六万本免费公版电子书库', '📕'),
        ('Z-Library', 'https://z-lib.io', '全球电子书与学术论文资源', '📚'),
        ('Scribd', 'https://www.scribd.com', '数字图书馆与有声书订阅', '📖'),
        ('百度文库', 'https://wenku.baidu.com', '中文在线文档分享平台', '📄'),
        ('道客巴巴', 'https://www.doc88.com', '中文文档在线阅读与下载', '📑'),
        ('豆瓣', 'https://www.douban.com', '中文图书电影音乐评分社区', '📚'),
        ('网易公开课', 'https://open.163.com', '网易旗下免费国内外公开课', '🎓'),
        ('腾讯课堂', 'https://ke.qq.com', '腾讯职业培训与考证实训', '📖'),
    ],
    'entertainment': [
        ('YouTube', 'https://www.youtube.com', '全球最大视频分享与创作平台', '🎬'),
        ('Netflix', 'https://www.netflix.com', '全球领先流媒体影视订阅', '📺'),
        ('Disney+', 'https://www.disneyplus.com', '迪士尼漫威星球大战流媒体', '🏰'),
        ('Max', 'https://www.max.com', 'HBO 华纳流媒体合家欢平台', '🎥'),
        ('Amazon Prime Video', 'https://www.primevideo.com', '亚马逊影视剧流媒体服务', '🎬'),
        ('Hulu', 'https://www.hulu.com', '美国热门电视节目流媒体', '📺'),
        ('Spotify', 'https://open.spotify.com', '全球第一音乐流媒体平台', '🎵'),
        ('Apple Music', 'https://music.apple.com', '苹果无损高音质音乐服务', '🍎'),
        ('YouTube Music', 'https://music.youtube.com', '谷歌旗下音乐流媒体应用', '🎶'),
        ('SoundCloud', 'https://soundcloud.com', '全球独立音乐人发布平台', '☁️'),
        ('Bandcamp', 'https://bandcamp.com', '独立音乐人直购与发现', '🎸'),
        ('Deezer', 'https://www.deezer.com', '法国高音质音乐流媒体', '🎼'),
        ('Tidal', 'https://tidal.com', '发烧级高保真音乐流媒体', '🎧'),
        ('Twitch', 'https://www.twitch.tv', '全球最大游戏直播与聊天平台', '🎮'),
        ('Steam', 'https://store.steampowered.com', 'PC 游戏数字发行最大平台', '🎮'),
        ('Epic Games Store', 'https://www.epicgames.com', '虚幻引擎厂商游戏商城', '🎮'),
        ('GOG.com', 'https://www.gog.com', 'CD Projekt 无DRM经典游戏', '🎮'),
        ('Roblox', 'https://www.roblox.com', '全球用户共创游戏元宇宙', '🎲'),
        ('IGN', 'https://www.ign.com', '全球权威游戏影视评测媒体', '🎮'),
        ('GameSpot', 'https://www.gamespot.com', '老牌游戏新闻与深度评测', '🕹️'),
        ('IMDb', 'https://www.imdb.com', '亚马逊旗下电影电视剧数据库', '🎬'),
        ('Rotten Tomatoes', 'https://www.rottentomatoes.com', '好莱坞影评烂番茄新鲜度', '🍅'),
        ('Letterboxd', 'https://letterboxd.com', '影迷社交日记与片单管理', '🎬'),
        ('Crunchyroll', 'https://www.crunchyroll.com', '全球最大动漫流媒体平台', '🍥'),
        ('Webtoon', 'https://www.webtoons.com', '韩国数字条漫阅读平台', '📱'),
        ('Pixiv', 'https://www.pixiv.net', '日本插画漫画创作分享社区', '🎨'),
        ('DeviantArt', 'https://www.deviantart.com', '全球艺术创作展示社区', '🖼️'),
        ('ArtStation', 'https://www.artstation.com', '专业CG艺术家作品集平台', '🎨'),
        ('TikTok', 'https://www.tiktok.com', '全球现象级短视频社交平台', '🎵'),
        ('Instagram', 'https://www.instagram.com', 'Meta 旗下图片视频分享社交', '📷'),
        ('Pinterest', 'https://www.pinterest.com', '全球灵感图片收藏与发现', '📌'),
        ('Vimeo', 'https://vimeo.com', '专业创作者高质量视频平台', '🎥'),
        ('B站', 'https://www.bilibili.com', '中国年轻世代文化社区', '📺'),
        ('抖音', 'https://www.douyin.com', '中国版短视频创作与分享', '🎵'),
        ('快手', 'https://www.kuaishou.com', '国民级短视频直播社区', '⚡'),
        ('QQ音乐', 'https://y.qq.com', '腾讯旗下正版音乐流媒体', '🎵'),
        ('网易云音乐', 'https://music.163.com', '音乐社区与个性推荐平台', '🎶'),
        ('酷狗音乐', 'https://www.kugou.com', '老牌数字音乐与K歌平台', '🎤'),
        ('起点中文网', 'https://www.qidian.com', '阅文集团原创网络文学旗舰', '📖'),
        ('晋江文学城', 'https://www.jjwxc.net', '中文女性向原创文学基地', '📚'),
        ('番茄小说', 'https://fanqienovel.com', '字节跳动免费网文阅读', '🍅'),
        ('虎牙直播', 'https://www.huya.com', '中国领先游戏直播平台', '🐯'),
        ('斗鱼直播', 'https://www.douyu.com', '武汉游戏电竞直播元老', '🐟'),
        ('AcFun', 'https://www.acfun.cn', '中国弹幕视频网站鼻祖', '🅰️'),
        ('豆瓣', 'https://www.douban.com', '中国文艺青年精神角落', '📚'),
        ('Kickstarter', 'https://www.kickstarter.com', '全球创意产品众筹平台', '🚀'),
        ('Patreon', 'https://www.patreon.com', '创作者会员制定阅赞助', '💎'),
        ('猫眼电影', 'https://maoyan.com', '中国电影票房与购票平台', '🎫'),
        ('淘票票', 'https://www.taopiaopiao.com', '阿里旗下电影在线选座', '🎬'),
        ('爱奇艺', 'https://www.iqiyi.com', '百度旗下综合视频平台', '📺'),
    ],
    'social': [
        ('Facebook', 'https://www.facebook.com', 'Meta 全球最大社交网络', '👤'),
        ('X (Twitter)', 'https://x.com', '马斯克旗下全球即时短消息', '🐦'),
        ('Instagram', 'https://www.instagram.com', '视觉化图片短视频社交', '📷'),
        ('LinkedIn', 'https://www.linkedin.com', '全球职业社交与求职平台', '💼'),
        ('TikTok', 'https://www.tiktok.com', '字节跳动全球短视频社交', '🎵'),
        ('Snapchat', 'https://www.snapchat.com', '年轻人阅后即焚趣味社交', '👻'),
        ('Reddit', 'https://www.reddit.com', '美国版贴吧兴趣社区聚合', '🦊'),
        ('Pinterest', 'https://www.pinterest.com', '灵感图片分享与收藏社交', '📌'),
        ('Discord', 'https://discord.com', '游戏玩家语音社区平台', '🎮'),
        ('Telegram', 'https://telegram.org', '加密即时通讯与频道广播', '✈️'),
        ('WhatsApp', 'https://www.whatsapp.com', '全球最多用户即时通讯', '💬'),
        ('Signal', 'https://signal.org', '开源端到端加密通讯', '🔒'),
        ('微信', 'https://www.wechat.com', '中国国民级超级社交应用', '💬'),
        ('QQ', 'https://im.qq.com', '中国老牌即时通讯软件', '🐧'),
        ('微博', 'https://weibo.com', '中国公开社交媒体广场', '🔴'),
        ('知乎', 'https://www.zhihu.com', '中国高质量问答知识社区', '❔'),
        ('贴吧', 'https://tieba.baidu.com', '百度旗下兴趣主题社区', '📌'),
        ('小红书', 'https://www.xiaohongshu.com', '生活方式种草社区电商', '📕'),
        ('豆瓣', 'https://www.douban.com', '文艺社区与书影音评分', '📚'),
        ('LINE', 'https://line.me', '日韩泰主流即时通讯应用', '🟢'),
        ('KakaoTalk', 'https://www.kakaocorp.com', '韩国国民级即时通讯', '💛'),
        ('Quora', 'https://www.quora.com', '英语世界高质量问答平台', '❓'),
        ('Tumblr', 'https://www.tumblr.com', '轻博客与亚文化创意社区', '📝'),
        ('Mastodon', 'https://mastodon.social', '去中心化联邦制社交网络', '🐘'),
        ('Bluesky', 'https://bsky.app', 'Twitter 创始人去中心化社交', '☁️'),
        ('Hacker News', 'https://news.ycombinator.com', 'Y Combinator 科技创业社区', '🔷'),
        ('Product Hunt', 'https://www.producthunt.com', '新产品发现与投票社区', '🚀'),
        ('Stack Exchange', 'https://stackexchange.com', '一百八十个问答社区网络', '🔗'),
        ('Flickr', 'https://www.flickr.com', '雅虎旗下照片存储分享', '📷'),
        ('500px', 'https://500px.com', '全球摄影师作品展示平台', '📸'),
        ('Medium', 'https://medium.com', '深度写作与阅读付费平台', '✍️'),
        ('Substack', 'https://substack.com', '独立作者付费 Newsletter', '📧'),
        ('VK', 'https://vk.com', '俄罗斯与东欧最大社交网络', '🇷🇺'),
        ('Nextdoor', 'https://nextdoor.com', '邻里社区私密社交平台', '🏘️'),
        ('Meetup', 'https://www.meetup.com', '线下兴趣小组聚会组织', '🤝'),
        ('Xing', 'https://www.xing.com', '德语区职业社交网络', '🟢'),
        ('GitHub', 'https://github.com', '开发者社交与开源协作', '🐙'),
        ('Dev.to', 'https://dev.to', '程序员技术文章社区', '✍️'),
        ('Dribbble', 'https://dribbble.com', '设计师社交与求职平台', '🏀'),
        ('OnlyFans', 'https://onlyfans.com', '创作者付费粉丝订阅平台', '🔞'),
        ('Threads', 'https://www.threads.net', 'Instagram 文字社交新应用', '🧵'),
        ('虎扑', 'https://www.hupu.com', '中国体育直男社区', '🏀'),
        ('NGA', 'https://bbs.nga.cn', '中国硬核游戏玩家论坛', '🎮'),
        ('V2EX', 'https://www.v2ex.com', '中国程序员创意社区', '💡'),
        ('CSDN', 'https://www.csdn.net', '中国最大IT技术社区', '🇨🇳'),
        ('掘金', 'https://juejin.cn', '字节跳动开发者技术社区', '💎'),
        ('SegmentFault', 'https://segmentfault.com', '中文技术问答与专栏', '🔧'),
        ('果壳', 'https://www.guokr.com', '泛科学兴趣社区与科普', '🔬'),
        ('少数派', 'https://sspai.com', '数字生活效率工具指南', '🧰'),
        ('酷安', 'https://www.coolapk.com', '安卓数码发烧友社区', '📱'),
    ],
    'tools': [
        # ===== 搜索引擎 =====
        ('Google', 'https://www.google.com', '全球第一搜索引擎，信息检索入口', '🔍'),
        ('Bing', 'https://www.bing.com', '微软搜索引擎，集成AI Copilot', '🔎'),
        ('DuckDuckGo', 'https://duckduckgo.com', '不追踪用户的隐私搜索引擎', '🦆'),
        ('百度', 'https://www.baidu.com', '中国最大的中文搜索引擎', '🔍'),
        ('Yandex', 'https://yandex.com', '俄罗斯最大搜索引擎与生态', '🇷🇺'),

        # ===== 在线文件转换 =====
        ('CloudConvert', 'https://cloudconvert.com', '支持200+格式的在线全能文件转换器', '🔄'),
        ('Convertio', 'https://convertio.co', '在线文档图片音视频格式互转', '🔄'),
        ('Zamzar', 'https://www.zamzar.com', '老牌在线文件格式转换服务', '📎'),
        ('Smallpdf', 'https://smallpdf.com', 'PDF压缩合并转换一站式工具', '📄'),
        ('iLovePDF', 'https://www.ilovepdf.com', 'PDF拆分合并压缩在线处理', '❤️'),
        ('PDF24 Tools', 'https://tools.pdf24.org', '德国免费PDF全套在线工具箱', '🛠️'),
        ('LightPDF', 'https://lightpdf.com', '免费在线PDF编辑转换工具', '💡'),
        ('Online-Convert', 'https://www.online-convert.com', '在线音视频文档电子书格式转换', '🔄'),
        ('FreeConvert', 'https://www.freeconvert.com', '免费在线视频音频图片转换', '🎬'),
        ('Aconvert', 'https://www.aconvert.com', '全能在线文件格式转换工具', '🔄'),
        ('TinyPNG', 'https://tinypng.com', '智能PNG/JPEG图片压缩优化', '🗜️'),
        ('Squoosh', 'https://squoosh.app', '谷歌出品的图片压缩Web应用', '📷'),

        # ===== 免费邮箱 =====
        ('Gmail', 'https://mail.google.com', '谷歌全球最受欢迎免费邮箱', '📧'),
        ('Outlook', 'https://outlook.live.com', '微软免费个人邮箱与日历', '📧'),
        ('Proton Mail', 'https://proton.me/mail', '瑞士端到端加密隐私邮箱', '🔐'),
        ('Yahoo Mail', 'https://mail.yahoo.com', '雅虎老牌免费大容量邮箱', '📧'),
        ('163邮箱', 'https://mail.163.com', '网易中国老牌免费电子邮箱', '📮'),
        ('QQ邮箱', 'https://mail.qq.com', '腾讯QQ配套免费邮箱服务', '📨'),
        ('Zoho Mail', 'https://www.zoho.com/mail', '印度免费企业级邮箱托管', '📬'),
        ('Tuta(nota)', 'https://tuta.com', '德国加密隐私免费邮箱', '🔒'),
        ('GMX', 'https://www.gmx.com', '德国老牌免费邮箱服务商', '📧'),
        ('Mail.com', 'https://www.mail.com', '200+域名可选免费邮箱', '✉️'),

        # ===== 虚拟电话 / 临时号码 =====
        ('Google Voice', 'https://voice.google.com', '谷歌免费美国虚拟电话号码', '📞'),
        ('TextNow', 'https://www.textnow.com', '美加免费虚拟号码通话短信', '📱'),
        ('TextFree', 'https://www.textfree.us', '美国免费虚拟号码收发短信', '💬'),
        ('Talkatone', 'https://www.talkatone.com', 'WiFi免费美国电话号码', '📞'),
        ('Dingtone', 'https://www.dingtone.me', '全球免费虚拟号码通话应用', '📲'),
        ('Burner', 'https://www.burnerapp.com', '美国一次性临时电话号码', '🔥'),
        ('Hushed', 'https://hushed.com', '美国加拿大私密第二号码', '🤫'),
        ('Sonetel', 'https://sonetel.com', '全球企业虚拟电话号码服务', '🌍'),
        ('Twilio', 'https://www.twilio.com', '全球最大云通讯API平台', '☁️'),
        ('接收短信', 'https://receive-smss.com', '免费在线接收验证码短信', '📩'),
        ('FreePhoneNum', 'https://freephonenum.com', '免费临时号码接收国际短信', '📱'),

        # ===== VPN / 代理 =====
        ('肥猫云VPN', 'https://ca01.fcvipaff.pro', '高速稳定科学上网VPN服务', '🐱'),
        ('Cloudflare WARP', 'https://one.one.one.one', 'Cloudflare免费加速与隐私DNS', '🛡️'),
        ('Proton VPN', 'https://protonvpn.com', '瑞士隐私保护免费VPN', '🔐'),
        ('Windscribe', 'https://windscribe.com', '加拿大免费增值模式VPN', '💨'),
        ('Hide.me', 'https://hide.me', '马来西亚无日志隐私VPN', '🫥'),
        ('Mullvad VPN', 'https://mullvad.net', '瑞典匿名现金支付VPN', '🎭'),
        ('TunnelBear', 'https://www.tunnelbear.com', '可爱界面简单易用VPN', '🐻'),

        # ===== 在线设计 / 图片工具 =====
        ('Canva', 'https://www.canva.com', '在线拖拽式平面设计神器', '🎨'),
        ('Figma', 'https://www.figma.com', '协作式UI设计行业标准', '🎨'),
        ('Adobe Express', 'https://www.adobe.com/express', 'Adobe免费在线快速设计', '🖌️'),
        ('Remove.bg', 'https://www.remove.bg', 'AI一键去除图片背景', '🖼️'),
        ('Photopea', 'https://www.photopea.com', '免费在线版Photoshop替代', '🖼️'),
        ('Pixlr', 'https://pixlr.com', '轻量在线图片编辑器', '📷'),

        # ===== 在线办公 / 笔记 =====
        ('Notion', 'https://www.notion.so', '全能型文档笔记与数据库', '📝'),
        ('Google Docs', 'https://docs.google.com', '谷歌在线文档协作编辑', '📄'),
        ('腾讯文档', 'https://docs.qq.com', '腾讯出品的在线协作文档', '📃'),
        ('石墨文档', 'https://shimo.im', '中国优雅的在线协作文档', '✍️'),
        ('语雀', 'https://www.yuque.com', '蚂蚁集团知识库与文档平台', '📚'),
        ('飞书文档', 'https://www.feishu.cn', '字节跳动旗下协作办公套件', '🪶'),
        ('金山文档', 'https://www.kdocs.cn', 'WPS在线协作办公平台', '📑'),

        # ===== 开发工具 =====
        ('Postman', 'https://www.postman.com', '全球API开发调试首选工具', '📮'),
        ('JSON Formatter', 'https://jsonformatter.org', 'JSON在线格式化校验转换', '📋'),
        ('cURL Converter', 'https://curlconverter.com', 'curl命令转各语言代码', '🔄'),
        ('CyberChef', 'https://gchq.github.io/CyberChef', '英国GCHQ网络数据瑞士军刀', '🧰'),
        ('IT-Tools', 'https://it-tools.tech', '开发者常用在线工具集合', '🔧'),
        ('QuickType', 'https://app.quicktype.io', 'JSON自动生成各语言类型定义', '⚡'),
        ('JWT.io', 'https://jwt.io', 'JSON Web Token在线调试解析', '🔑'),

        # ===== 在线存储 / 传输 =====
        ('Dropbox', 'https://www.dropbox.com', '先驱级云端文件存储同步', '📦'),
        ('Google Drive', 'https://drive.google.com', '谷歌免费15GB云存储', '💾'),
        ('MEGA', 'https://mega.io', '新西兰端到端加密云存储', '🔐'),
        ('WeTransfer', 'https://wetransfer.com', '免费2GB大文件临时传输', '📤'),
        ('Send Anywhere', 'https://send-anywhere.com', '跨设备点对点文件快传', '📲'),
        ('奶牛快传', 'https://cowtransfer.com', '中国极简大文件分享服务', '🐄'),
        ('文叔叔', 'https://www.wenshushu.cn', '国内不限速大文件传输', '📁'),
        ('TeraBox', 'https://www.terabox.com', '百度海外1TB免费云存储', '💾'),

        # ===== 其他实用工具 =====
        ('Wolfram Alpha', 'https://www.wolframalpha.com', '计算知识引擎，数学求解神器', '🧮'),
        ('Time.is', 'https://time.is', '精确到毫秒的全球标准时间', '⏰'),
        ('Draw.io', 'https://app.diagrams.net', '免费开源的在线流程图工具', '📐'),
        ('Excalidraw', 'https://excalidraw.com', '手绘风格在线协作白板', '✏️'),
        ('Cronitor', 'https://cronitor.io', '定时任务监控与报警服务', '⏱️'),
        ('DownDetector', 'https://downdetector.com', '全球服务宕机实时检测', '📉'),
        ('Speedtest', 'https://www.speedtest.net', '全球最知名网络测速工具', '🚀'),
        ('VirusTotal', 'https://www.virustotal.com', '谷歌旗下多引擎文件病毒扫描', '🛡️'),
        ('Have I Been Pwned', 'https://haveibeenpwned.com', '检查邮箱是否泄露过密码', '🔓'),
        ('Temp Mail', 'https://temp-mail.org', '免费一次性临时邮箱地址', '📧'),
        ('10分钟邮箱', 'https://10minutemail.net', '十分钟有效临时邮箱服务', '⏳'),
        ('Guerrilla Mail', 'https://www.guerrillamail.com', '开源可丢弃临时邮箱', '✉️'),
        ('Privnote', 'https://privnote.com', '阅后即焚加密便签分享', '🔥'),
        ('DeepL', 'https://www.deepl.com', 'AI神经网络高质量翻译', '🌍'),
        ('Google Translate', 'https://translate.google.com', '谷歌免费百种语言翻译', '🌍'),
        ('Grammarly', 'https://www.grammarly.com', 'AI英文写作校对助手', '✍️'),
    ],
}

def main():
    conn = mysql.connector.connect(**DB, buffered=True)
    c = conn.cursor()

    # 清空
    c.execute('DELETE FROM bookmarks')
    print(f'已清空所有书签')

    # 重新插入
    total = 0
    cat_names = {'work': '工作', 'study': '学习', 'entertainment': '娱乐', 'social': '社交', 'tools': '工具'}

    for cat_key in ['work', 'study', 'entertainment', 'social', 'tools']:
        sites = SITES[cat_key]
        count = 0
        for title, url, desc, icon in sites:
            c.execute(
                'INSERT INTO bookmarks (title, url, description, icon, category) VALUES (%s,%s,%s,%s,%s)',
                (title.strip()[:100], url.strip()[:500], desc.strip()[:200], icon, cat_key)
            )
            count += 1
        conn.commit()
        total += count
        print(f'  {cat_names[cat_key]}: {count} 个网站已入库')

    c.execute('SELECT COUNT(*) FROM bookmarks')
    final = c.fetchone()[0]
    conn.close()
    print(f'\n=== 总计 {final} 个网站，全部中文描述 ===')

if __name__ == '__main__':
    main()
